import type { Metadata } from "next";
import "./globals.css";
import './modal.css';
import Header from "@/components/headerAndFooter/Header";
import ReduxProvider from "@/components/ReduxProvider";
import Footer from "@/components/headerAndFooter/Footer";
import AuthModals from "@/components/authComponents/AuthModals";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <ReduxProvider>
          <Header />
          <AuthModals />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
